package com.example.supersmartkeyapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFFC9A227)
val onPrimaryDark = Color(0xFF1A1A1A)
val primaryContainerDark = Color(0xFFC9A227)
val onPrimaryContainerDark = Color(0xFF1A1A1A)
val secondaryDark = Color(0xFF286241)
val onSecondaryDark = Color(0xFFFAFAFA)
val secondaryContainerDark = Color(0xFF1A1A1A)
val onSecondaryContainerDark = Color(0xFFFAFAFA)
val tertiaryDark = Color(0xFFCAC5C5)
val onTertiaryDark = Color(0xFF323030)
val tertiaryContainerDark = Color(0xFF4CAF50)
val onTertiaryContainerDark = Color(0xFFFAFAFA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF9B2226)
val onErrorContainerDark = Color(0xFFFAFAFA)
val backgroundDark = Color(0xFF0B3D2E)
val onBackgroundDark = Color(0xFFFAFAFA)
val surfaceDark = Color(0xFF0B3D2E)
val onSurfaceDark = Color(0xFFC9A227)
val surfaceVariantDark = Color(0xFF0B3D2E)
val onSurfaceVariantDark = Color(0xFFC9A227)
val outlineDark = Color(0xFFC9A227)
val outlineVariantDark = Color(0xFFC9A227)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFAFAFA)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF5F5E5E)
val surfaceDimDark = Color(0xFF0B3D2E)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A2A)
val surfaceContainerHighestDark = Color(0xFF0B3D2E)